# NumPy

In [ ]:
import numpy as np

## 03. The NumPy array

In [4]:
a1 = np.array([1,2,3])
a1.shape
#(3,)
np.arange(0,15)
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
np.arange(0,15,2)
#array([ 0,  2,  4,  6,  8, 10, 12, 14])
np.arange(1,15,2)
#array([ 1,  3,  5,  7,  9, 11, 13])

np.linspace(0,100,3)
#array([  0.,  50., 100.])
np.linspace(0,100,3, endpoint=False)
#array([ 0.        , 33.33333333, 66.66666667])

(3,)

## 04. Basic operations with arrays

In [8]:
##SHAPE

a = np.arange(12)
##a.reshape(4,3)
#array([[ 0,  1,  2],
#       [ 3,  4,  5],
#       [ 6,  7,  8],
#       [ 9, 10, 11]])

##a.reshape(2,2,3)
#array([[[ 0,  1,  2],
#        [ 3,  4,  5]],
#
#       [[ 6,  7,  8],
#        [ 9, 10, 11]]])

## VECTEURS
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
A*B                
#array([[2, 0],
#       [0, 4]])
A.dot(B)                
#array([[5, 4],
#       [3, 4]])

## CONCATENATION
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
# d ==> array([11, 22, 18,  7,  6,  1,  3,  5])

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.concatenate((a, b), axis=0)
#array([[1, 2],
#       [3, 4],
#       [5, 6],
#       [7, 8]])

np.concatenate((a, b), axis=1)
#array([[1, 2, 5, 6],
#       [3, 4, 7, 8]])

array([[5, 4],
       [3, 4]])

## 05. Indexing and slicing

In [22]:
a = np.reshape(np.arange(12),(4,3))
a
#array([[ 0,  1,  2],
#       [ 3,  4,  5],
#       [ 6,  7,  8],
#       [ 9, 10, 11]])

a[1:3,0]
#array([3, 6])

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
a
##la vue modifi l'objet d'origine !?!?!? WTF

b = np.array([[11, 22],[33, 44],[55, 66]])
c = b.reshape((b.shape[0], b.shape[1], 1))
c
## ?? 

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

## 06. Exercise: slicing arrays

In [103]:
oneDim = np.arange(start = 1, stop=37) #1
twoDim = oneDim.reshape(6,6) #2
twoDim[:,1]#3
twoDim[0:2,4:6]#4
twoDim[5,4:6]#5
twoDim[2::2,0::2]#4#5

array([[13, 15, 17],
       [25, 27, 29]])

## 07. Solution to slicing arrays

In [87]:
#tiptop

array([[13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

## 08. Boolean masking of arrays

In [110]:
a = np.reshape(np.arange(12),(4,3))
a>8
#array([[False, False, False],
#       [False, False, False],
#       [False, False, False],
#       [ True,  True,  True]], dtype=bool)
a[a>8]
#array([ 9, 10, 11])
a[a>8]=0
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

## 09. Broadcasting

Broadcasting rule
* Take the tuples giving the shape of each array.
* If one of the tuples is shorter (because the array has fewer axes) then pad it with 1's from the front until it has the same size as the longer tuple.
* Now compare the tuples element by element and check whether at each position either (i) the entries are equal, or (ii) one of the entries is 1. If this is true for each position, then broadcasting can occur. Otherwise, broadcasting cannot occur.

## 10. Exercise: distance matrix with broadcasting

In [147]:
dist_to_origin = np.array([0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391])
dist_to_origin
alter_dist_to_origin = np.reshape(dist_to_origin,(10,1))
alter_dist_to_origin
np.absolute(alter_dist_to_origin - dist_to_origin)

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

## 11. Solution to distance matrix with broadcasting

In [149]:
#top

## 12. Copies and views