# 02. Why do we need linear algebra for data science?

* associative: A(BC)=(AB)C
* distributive: A(B+C)=AB+AC
* not commutative AB≠BA



In [8]:
import numpy as np

x = [5,7,-2,2]
y = [4,5,12,0]

# Linear algebra version
np.array(x)*np.array(y)
# Out: array([ 20,  35, -24,   0])

array([ 20,  35, -24,   0])

## 04. Vectors and matrices in NumPy

In [9]:
A = np.array([[1,2],[2,1]])
B =np.array([[1,5],[0,2]])
#A+5*B
#Out: array([[ 6, 27],[ 2, 11]])
np.dot(A, B)

array([[ 1,  9],
       [ 2, 12]])

In [10]:
a = np.array([0, 1, 2])
a.T

array([0, 1, 2])

In [11]:
b = np.array([[0],[1],[2]])
b.T

array([[0, 1, 2]])

In [12]:
a = np.array([
 [0],
 [7]
])
b = np.array([
 [1,2],
 [0,6]
])
c = np.array([
 [2,2]
])
a.shape
#Out: (2,1)
b.shape
#Out: (2,2)
c.shape
#Out: (1,2)
a*b
#Out: array([[ 0,  0],[ 0, 42]])

array([[ 0,  0],
       [ 0, 42]])

## 05. The inverse of a matrix

## 06. The linalg module in NumPy

In [13]:
A = np.array([[3,4],[2,3]])
A.T
#Out: array([[3, 2],[4, 3]])
np.linalg.inv(A)
#Out: array([[ 3., -4.], [-2.,  3.]])

array([[ 3., -4.],
       [-2.,  3.]])

In [14]:
np.linalg.matrix_rank(A)
#Out: 2

2

## 07. Exercise: solving a system of linear equations

In [15]:
# system
A = np.array([[2,1,1],[-5,-3,0],[1,1,-1]])
b = np.array([[-1],[1],[-2]])
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1]])

In [16]:
# 2 rank of A
np.linalg.matrix_rank(A)

3

In [17]:
#inverse of A 
A_inv=np.linalg.inv(A)

In [18]:
np.dot(A_inv,b)

array([[  7.],
       [-12.],
       [ -3.]])

In [19]:
np.linalg.solve(A,b)

array([[  7.],
       [-12.],
       [ -3.]])